In [1]:
import numpy as np

In [16]:
a = np.array([1,2,3], dtype='int16')
b = np.array([[9,8,7],[6,5,4]])
print(a)
print(b)

[1 2 3]
[[9 8 7]
 [6 5 4]]


In [12]:
#GET DISMENSION
a.ndim

(2, 3)

In [11]:
#GET SHAPE
b.shape

(2, 3)

In [17]:
#GET TYPE
a.dtype

dtype('int16')

In [18]:
#GET SIZE
a.itemsize

2